# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-08 15:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainsite', '0002_team'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team',
            name='member',
        ),
        migrations.AddField(
            model_name='team',
            name='leader',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='mainsite.User'),
        ),
        migrations.AddField(
            model_name='team',
            name='name',
            field=models.CharField(default='none', max_length=20),
        ),
    ]
