# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-08 15:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainsite', '0003_auto_20170908_2303'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='name',
            field=models.CharField(default='none', max_length=20, verbose_name='\u540d\u79f0'),
        ),
    ]
