# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-10 04:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainsite', '0004_auto_20170908_2311'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='code',
            field=models.CharField(default='00000000', max_length=8, verbose_name='\u9080\u8bf7\u7801'),
        ),
    ]
