# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-25 09:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainsite', '0005_team_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='mate_one',
            field=models.CharField(default='none', max_length=20, verbose_name='\u540d\u79f0'),
        ),
    ]
